# TorchRL memory replay buffer
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ReinforcementLearning-RUG/ReinforcementLearning-tutorials/blob/main/notebooks/replay.ipynb)

In [16]:
# Install dependencies for google colab
%pip install torchrl


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [17]:
import torch
from torchrl.data import ReplayBuffer, LazyTensorStorage

buf = ReplayBuffer(storage=LazyTensorStorage(
                    max_size=5,
                    device="cuda" if torch.cuda.is_available() else "cpu"),
                    batch_size=2)        # Sample 2 trajectories each time.

trajectory1 = (torch.as_tensor(1), torch.as_tensor(2), torch.as_tensor(3), torch.as_tensor(4))    # S, A, R, S
trajectory2 = (torch.as_tensor(5), torch.as_tensor(6), torch.as_tensor(7), torch.as_tensor(8))
trajectory3 = (torch.as_tensor(9), torch.as_tensor(10), torch.as_tensor(11), torch.as_tensor(12))

buf.add(trajectory1)
buf.add(trajectory2)
buf.add(trajectory3)

buf.sample()     # prints state batch, action batch, reward batch and next state batch.


(tensor([1, 1], device='cuda:0'),
 tensor([2, 2], device='cuda:0'),
 tensor([3, 3], device='cuda:0'),
 tensor([4, 4], device='cuda:0'))